language: perl
perl:
  - 5.8
  - 5.10
  - 5.12
  - 5.18

before_script:
    - psql -c 'create database nessy;' -U postgres
    - git clone https://github.com/genome/nessy-server.git
    - pushd nessy-server
    - sudo pip install -r requirements.txt
    - LOCKING_DB='postgres://postgres@localhost/nessy' ./devserver &
    - popd

script:
    - NESSY_SERVER_URL=http://localhost:5000 prove -I t/lib --lib --verbose --recurse t/
